// src/svelte/DrawCanvas.svelte
<script lang="ts">
  /**
   * Svelte host for DrawEngine: mounts one <canvas>, tracks size via
   * ResizeObserver, and forwards pointer + keyboard input. Thin adapter — no
   * drawing or tool logic lives here; bindCanvas + the engine own it.
   */
  import { onMount } from "svelte";
  import type { DrawEngine } from "../engine";
  import { LIGHT_THEME } from "../types";
  import { bindCanvasAsync } from "../host/bindCanvas";
  import type { DrawCanvasProps, HostCallbacks } from "../host/types";

  let {
    scene,
    theme = LIGHT_THEME,
    defaultStroke,
    className = "",
    ariaLabel = "Drawing canvas",
    onReady,
    onCameraChange,
    onToolChange,
    onSelectionChange,
    onRequestTextEdit,
    onSceneChange,
    onContextMenu,
    onToolLockChange,
  }: DrawCanvasProps = $props();

  let containerEl: HTMLDivElement | undefined;
  let canvasEl: HTMLCanvasElement | undefined;
  let engine: DrawEngine | null = null;
  let ready = $state(false);

  const callbacks: HostCallbacks = {};

  $effect(() => {
    callbacks.onCameraChange = onCameraChange;
    callbacks.onToolChange = onToolChange;
    callbacks.onSelectionChange = onSelectionChange;
    callbacks.onRequestTextEdit = onRequestTextEdit;
    callbacks.onSceneChange = onSceneChange;
    callbacks.onContextMenu = onContextMenu;
    callbacks.onToolLockChange = onToolLockChange;
  });

  onMount(() => {
    if (!canvasEl || !containerEl) return;
    let destroy: (() => void) | undefined;
    let cancelled = false;
    void bindCanvasAsync({ canvas: canvasEl, container: containerEl, callbacks, onReady }).then((bound) => {
      if (cancelled) {
        bound.destroy();
        return;
      }
      engine = bound.engine;
      destroy = bound.destroy;
      ready = true;
    });
    return () => {
      cancelled = true;
      ready = false;
      engine = null;
      destroy?.();
    };
  });

  $effect(() => {
    if (!ready) return;
    if (scene) engine?.setScene(scene);
  });

  $effect(() => {
    if (!ready) return;
    engine?.setTheme(theme);
  });

  $effect(() => {
    if (!ready) return;
    if (defaultStroke) engine?.setNextStyle({ strokeColor: defaultStroke });
  });
</script>

<!--
  The rule assumes a nonnegative tabindex on a non-widget role is a mistake. Here it is
  the point: this is the drawing surface, it carries `role="application"` precisely
  because it handles its own keys, and every shortcut — tool selection, delete, nudge,
  undo — needs it focusable. Removing the tabindex would make the whole board
  keyboard-inaccessible, which is the opposite of what the rule is for.
-->
<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
  bind:this={containerEl}
  class={className}
  role="application"
  aria-label={ariaLabel}
  tabindex={0}
  style="position: relative; width: 100%; height: 100%; touch-action: none; outline: none;"
>
  <canvas
    bind:this={canvasEl}
    aria-hidden="true"
    tabindex={-1}
    style="display: block; width: 100%; height: 100%;"
  ></canvas>
</div>

// src/react/DrawCanvas.tsx
/**
 * The React host for DrawEngine: mounts one <canvas> and forwards it to
 * bindCanvas after WASM init. Thin adapter — drawing and tool chords live in host/.
 */

import { useEffect, useRef } from "react";
import { bindCanvasAsync } from "../host/bindCanvas";
import type { DrawCanvasProps, HostCallbacks } from "../host/types";
import { LIGHT_THEME } from "../types";
import type { DrawEngine } from "../engine";

export type { DrawCanvasProps } from "../host/types";

export function DrawCanvas({
  scene,
  theme = LIGHT_THEME,
  defaultStroke,
  className,
  ariaLabel = "Drawing canvas",
  onReady,
  onCameraChange,
  onToolChange,
  onSelectionChange,
  onRequestTextEdit,
  onSceneChange,
  onContextMenu,
  onToolLockChange,
}: DrawCanvasProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<DrawEngine | null>(null);
  const sceneRef = useRef(scene);
  const themeRef = useRef(theme);
  const strokeRef = useRef(defaultStroke);
  sceneRef.current = scene;
  themeRef.current = theme;
  strokeRef.current = defaultStroke;
  const callbacksRef = useRef<HostCallbacks>({});
  const callbacks = callbacksRef.current;
  callbacks.onCameraChange = onCameraChange;
  callbacks.onToolChange = onToolChange;
  callbacks.onSelectionChange = onSelectionChange;
  callbacks.onRequestTextEdit = onRequestTextEdit;
  callbacks.onSceneChange = onSceneChange;
  callbacks.onContextMenu = onContextMenu;
  callbacks.onToolLockChange = onToolLockChange;

  useEffect(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) return;
    let cancelled = false;
    let destroy: (() => void) | undefined;
    void bindCanvasAsync({ canvas, container, callbacks, onReady }).then((bound) => {
      if (cancelled) {
        bound.destroy();
        return;
      }
      engineRef.current = bound.engine;
      destroy = bound.destroy;
      if (sceneRef.current) bound.engine.setScene(sceneRef.current);
      bound.engine.setTheme(themeRef.current);
      if (strokeRef.current) bound.engine.setNextStyle({ strokeColor: strokeRef.current });
    });
    return () => {
      cancelled = true;
      destroy?.();
      engineRef.current = null;
    };
    // Engine is created once for the lifetime of the mount; prop syncs live in
    // the effects below.
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount-once bind; callbacks bag is mutated in render
  }, []);

  useEffect(() => {
    if (scene) engineRef.current?.setScene(scene);
  }, [scene]);

  useEffect(() => {
    engineRef.current?.setTheme(theme);
  }, [theme]);

  useEffect(() => {
    if (defaultStroke) engineRef.current?.setNextStyle({ strokeColor: defaultStroke });
  }, [defaultStroke]);

  return (
    <div
      ref={containerRef}
      className={className}
      role="application"
      aria-label={ariaLabel}
      tabIndex={0}
      style={{ position: "relative", width: "100%", height: "100%", touchAction: "none", outline: "none" }}
    >
      <canvas ref={canvasRef} aria-hidden="true" tabIndex={-1} style={{ display: "block", width: "100%", height: "100%" }} />
    </div>
  );
}
